package com.camachoyury.validia.data.ai

/**
 * Contract for the on-device inference engine.
 *
 * Active implementation:
 *  - [LiteRtInferenceEngine] → com.google.ai.edge.litertlm:litertlm-android:0.10.0
 *
 * The engine handles internally:
 *  - The model chat template (system instruction)
 *  - EOS tokens (native end-of-generation)
 *  - Token-by-token streaming via Flow<Message>
 *  - GPU / NPU acceleration (configurable via Backend)
 */
interface LocalInferenceEngine {
    /**
     * Initializes the engine by loading the model into memory.
     * Expensive operation (~2-8 sec depending on device) — always on Dispatchers.IO.
     *
     * @param modelPath Asset name (.litertlm) or absolute path to the file.
     */
    suspend fun initialize(modelPath: String)

    /**
     * Runs local inference with the loaded model.
     *
     * Unlike the MediaPipe version, there is NO need to manually build
     * the chat template. The SDK handles the model format
     * (system instruction, user turn, EOS) natively.
     *
     * @param systemPrompt Model instructions (few-shot examples, rules, format).
     * @param userInput    User input text to process.
     * @param onToken      Callback invoked for each token chunk as it is generated.
     * @return Text generated by the model (expected: JSON array).
     */
    suspend fun generate(
        systemPrompt: String,
        userInput: String,
        onToken: (String) -> Unit = {}
    ): String

    /** Releases native resources. Call in ViewModel.onCleared(). */
    fun close()
}
